const = {"button_ipadX": 6,
         "button_ipadY": 6,
         "button_padX": 10,
         "button_padY": 10,
         "label_title_padX": 15,
         "label_title_padY": 10,
         "label_ipadY": 4,
         "label_ipadX": 4,
         "label_normal_padX": 10,
         "label_normal_padY": 10,
         "label_font_normal": ("Segoe UI", 10),
         "label_font_title": ("Segoe UI", 14, 'bold'),
         "entry_padX": 5,
         "entry_padY": 5,
         "entry_ipadX": 4,
         "entry_ipadY": 4}
